### ISSUE TITLE
Clicking the '.' button multiple times adds multiple periods.

### ISSUE THREAD

**Issue by jsdevel** [thevon1/Tom-s-Journal#3]

**Comment by thevon1** [comment]
what is the best way to go about this?
can i modify this method to allow a regExp?

$scope.setDecimal = function (decimalEntered) {
        if ($scope.operator){
            $scope.rightOperand += decimalEntered;
        };
        else {$scope.leftOperand += decimalEntered;
        };

**Comment by jsdevel** [comment]
if the operand has a `'.'` in it, then don't do anything, if it doesn't, then allow the `'.'` to be added.  `String.prototype` has an `.indexOf` method that will return the index of a character if it is present in the string.  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf

**Comment by thevon1** [comment]
completed
